# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kilnx < Formula
  desc "Declarative backend language for the htmx era"
  homepage "https://kilnx.org"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.3/kilnx_darwin_amd64.tar.gz"
      sha256 "5f84195dc15f26a2338236000a4f9f8f62c7f60956be823ad3ebb43d56b066fa"

      define_method(:install) do
        bin.install "kilnx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.3/kilnx_darwin_arm64.tar.gz"
      sha256 "e02dfa3a96ec63d5091abc536b48d5b5d0537e727a3188e3b4a0892611bdf2d3"

      define_method(:install) do
        bin.install "kilnx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.3/kilnx_linux_amd64.tar.gz"
      sha256 "2b95179795e9b9bb6fcb9bdb90b9c80ed19a349f2fe2e098088fcc497f5ed805"
      define_method(:install) do
        bin.install "kilnx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.3/kilnx_linux_arm64.tar.gz"
      sha256 "785eb06c3c1a6c46f4f8eb729055251ffaaa185a3837bec571d0cb3b89238148"
      define_method(:install) do
        bin.install "kilnx"
      end
    end
  end

  test do
    system "#{bin}/kilnx", "version"
  end
end
