# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kilnx < Formula
  desc "Declarative backend language for the htmx era"
  homepage "https://kilnx.org"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.2/kilnx_darwin_amd64.tar.gz"
      sha256 "9cca458f4d9d9a0631308d4d741262f6492cb13bdc092aa37cbc59b7e70f2c5c"

      define_method(:install) do
        bin.install "kilnx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.2/kilnx_darwin_arm64.tar.gz"
      sha256 "4da79b9e7f93a7b98510cc87d827ece3778f7ca7cbc23499e506b1f543097f82"

      define_method(:install) do
        bin.install "kilnx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.2/kilnx_linux_amd64.tar.gz"
      sha256 "3fbbd92cded4b30b14056eddf94a09acad46a8d49cce16f24f9bb10463807eb0"
      define_method(:install) do
        bin.install "kilnx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kilnx-org/kilnx/releases/download/v0.1.2/kilnx_linux_arm64.tar.gz"
      sha256 "b3187381e23136ab92e18c5c15d4998d37397560c1ce41046b63f0e4b20a15bd"
      define_method(:install) do
        bin.install "kilnx"
      end
    end
  end

  test do
    system "#{bin}/kilnx", "version"
  end
end
